### ISSUE TITLE
add fmt and clippy check in ci check

### ISSUE THREAD

**Issue by asukaminato0721** [nobuyuki83/del-geo#3]
I notice that there seems missing fmt and clippy check in ci

```
cargo fmt --check
cargo clippy -- -Dwarnings
```

also cross platform ci seems could be added.

mind I make a PR to add them?

**Comment by nobuyuki83** [comment]
Good idea. please add `clippy` and `fmt` in the ci.  I think cross-platform ci is not necessary as `del-geo` does not do anything complicated.
